### ISSUE TITLE
Transition to Ember CLI

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-server#138]
I dunno. Go for it!

**Comment by killpack** [comment]
![image](https://cloud.githubusercontent.com/assets/3970187/6141325/e13ba610-b171-11e4-8157-8937785aa2b6.png)

**Comment by gschorkopf** [comment]
![panda](https://cloud.githubusercontent.com/assets/2623668/6141471/0dc07a6a-b174-11e4-9dcd-0e46800f5eae.jpg)
