### ISSUE TITLE
Clean Way to Change the Name of this Repo

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-server#141]
'frolfr-server'?

**Comment by killpack** [comment]
Sounds good.
I think you'll just need to rename this in Github (it'll warn you about All The Bad Repercussions of doing this), and then we'll all need to update our Git remotes. I don't think it'll be too painful.

Suggestion: Frolfr Github org??? Or is that overkill, y'think?

**Comment by gschorkopf** [comment]
Added a frolfr github org and forked over the repos. Are there other things to be done? We should reset our origins on frolfr / frolfr-client to the frolfr orgs repos, right?

**Comment by gschorkopf** [comment]
I've never made an org before. EXCITEMENT MOUNTING>

**Comment by killpack** [comment]
I think the only thing to do is to change your remotes locally, and then you'll be good to go.

**Comment by killpack** [comment]
Actually, maybe this is what you want to do:
https://help.github.com/articles/transferring-a-repository/

**Comment by gschorkopf** [comment]
@killpack @pdougall1 please point your remote origins to the new repos:

https://github.com/frolfr/frolfr-server
https://github.com/frolfr/frolfr-client
