### ISSUE TITLE
Unable to upload an avatar

### ISSUE THREAD

**Issue by ultimatemonty** [frolfr/frolfr-server#158]
I can select the image but I have no way to save/upload it. Save button remains disabled. Seems like this might should be an issue for the client project but I can't create an issue there.

**Comment by gschorkopf** [comment]
:+1: I think this might have to do with the size of the file. I wonder if there's a way in the avatars#create action to change the filesize to be small enough for our `Cloudinary::Uploader` to handle.

**Comment by gschorkopf** [comment]
Let's look into: http://cloudinary.com/documentation/rails_integration#getting_started_guide, which could resolve both this issue and "squarify-ing" things #121 

```
Cloudinary::Uploader.upload(params[:image],
                            :public_id => "sample_id",
                            :crop => :limit, :width => 2000, :height => 2000,
                            :eager => [
                              { :width => 200, :height => 200, 
                                :crop => :thumb, :gravity => :face,
                                :radius => 20, :effect => :sepia },
                              { :width => 100, :height => 150, 
                                :crop => :fit, :format => 'png' }
                            ],                                     
                            :tags => ['special', 'for_homepage'])
```

**Comment by gschorkopf** [comment]
@ultimatemonty looks like the fix was pretty straightforward: https://github.com/frolfr/frolfr-server/pull/159

I'll push once this gets merged in.

**Comment by ultimatemonty** [comment]
@gschorkopf you are the man! I'll try it out when I have the chance!

**Comment by gschorkopf** [comment]
I'm running into issues on a phone. May have to revisit this.

**Comment by gschorkopf** [comment]
Hummm... it's working locally, but I can replicate the issue on production (for mobile). GAH. Reopening this for now, will investigate soon.

**Comment by gschorkopf** [comment]
![](https://files.slack.com/files-pri/T024FA2V1-F04AJDNFR/screen_shot_2015-04-07_at_1.42.56_pm.png)

**Comment by gschorkopf** [comment]
Issue was we weren't using the config.apiPath in our file uploader
