### ISSUE TITLE
500 Server Error on /api/password_resets

### ISSUE THREAD

**Issue by gesmith** [frolfr/frolfr-server#183]
![screen shot 2015-08-24 at 7 32 45 pm](https://cloud.githubusercontent.com/assets/2042451/9455241/f556501e-4a96-11e5-8445-f3be1298cee1.png)

To reproduce: Navigate to http://frolfr.com/password/reset, enter email, hit "send reset email" button.

**Comment by gschorkopf** [comment]
Wow! Apologies that we've abandoned frolfr for this long. Lemme tackle this today.

**Comment by gschorkopf** [comment]
Issue number 1) Google now generally prevents 3rd party apps from using credentials to send mail. We should probably use a different service or something. But it's working now. However, 2) I found a separate issue on the password change form of 401 `Uncaught TypeError: a.default.validPassword is not a function`

**Comment by gschorkopf** [comment]
Should be good! Feel free to reopen if you have any issues!
