### ISSUE TITLE
Ensure that frolfr-client works on a new computer

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-server#193]
Acceptance criteria: do this, https://github.com/frolfr/frolfr-client#installation

If additional steps are needed, write it in the README

**Comment by ultimatemonty** [comment]
@gschorkopf I'd highly recommend getting ember-cli-mirage setup on the client so the Rails API isn't needed for development. 

Now that the 1.13 update is merged in I'll start banging on getting mirage setup
