### ISSUE TITLE
[CLIENT] Convert sessions controller to a service

### ISSUE THREAD

**Issue by ultimatemonty** [frolfr/frolfr-server#196]
Using controllers for most things is now considered bad practice. Using the controller `needs` API is considered an offense punishable by extreme Twitter shaming.

Let's not be shamed and instead convert the sessions controller to a service.

**Comment by gschorkopf** [comment]
👍 Additionally, might be worthwhile to just go forth with #152

**Comment by ultimatemonty** [comment]
@gschorkopf agreed. I'll close this in favor of #152
