### ISSUE TITLE
[SERVER] Profiles page throwing an HTTP 500

### ISSUE THREAD

**Issue by ultimatemonty** [frolfr/frolfr-server#199]
When trying to visit the Profiles page (/profile/stats) the server is returning an HTTP 500. I've included the request and response headers - there is no response body.

Request
```
GET /api/profile_stat_logs/current HTTP/1.1
Host: frolfr.herokuapp.com
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://frolfr.com
Authorization: <valid but removed>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
DNT: 1
Referer: http://frolfr.com/profile/stats
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```

Response:
```
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 48
X-Request-Id: 62df2ec1-91f7-4fe2-b4fd-93af0b702c0b
X-Runtime: 0.041544
Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
Date: Wed, 10 Aug 2016 13:02:26 GMT
Via: 1.1 vegur
```

**Comment by gschorkopf** [comment]
I'll look into it!

**Comment by gschorkopf** [comment]
Good catch! Thanks for the feedback... we tried to improve the "first time" user experience a while ago, but clearly there are still bugs to work out.

**Comment by gschorkopf** [comment]
That PR should fix your issue. Also: want me to combine your two accounts? (The one you'd made before, and the one you had to make because of the bug in #183

**Comment by ultimatemonty** [comment]
@gschorkopf yeah that'd be great! also - thanks for fixing the bug!
